### ISSUE TITLE
multi class

### ISSUE THREAD

**Issue by ttjjyys** [xq141839/DCSAU-Net#30]
您好，SegPC2021数据集属于多类分割，在跑SegPC2021时，项目有需要改动的地方吗

**Comment by 18834114892** [comment]
您好，处理SegPC2021多分类数据集的代码也可以发我一下吗，我的邮箱是[2453499915@qq.com](mailto:2453499915@qq.com) 万分感谢，自己调整了半天整了一堆错出来

**Comment by 18834114892** [comment]
您好作者，我修改了train的dataloader和损失函数，但是仍然报错
Traceback (most recent call last):
  File "D:\TJY\DCSAU-Net-main\train_segpc.py", line 377, in <module>
    model_ft, Loss_list, Accuracy_list = train_model(model_ft, criterion, optimizer_ft, scheduler,
  File "D:\TJY\DCSAU-Net-main\train_segpc.py", line 173, in train_model
    for inputs, labels, image_id in dataloaders[phase]:
  File "D:\anaconda3\envs\tjy\lib\site-packages\torch\utils\data\dataloader.py", line 631, in __next__
    data = self._next_data()
  File "D:\anaconda3\envs\tjy\lib\site-packages\torch\utils\data\dataloader.py", line 1346, in _next_data
    return self._process_data(data)
  File "D:\anaconda3\envs\tjy\lib\site-packages\torch\utils\data\dataloader.py", line 1372, in _process_data
    data.reraise()
  File "D:\anaconda3\envs\tjy\lib\site-packages\torch\_utils.py", line 705, in reraise
    raise exception
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "D:\anaconda3\envs\tjy\lib\site-packages\torch\utils\data\_utils\worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
  File "D:\anaconda3\envs\tjy\lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\anaconda3\envs\tjy\lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\TJY\DCSAU-Net-main\data_loading.py", line 33, in __getitem__
    image_path = os.path.join(image_folder,os.listdir(image_folder)[0])
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'SegPC/9418.png\\images/'可以帮我看下问题吗，谢谢您

**Comment by 18834114892** [comment]
image_path = os.path.join(image_folder,os.listdir(image_folder)[0])您好，我print了一下image_folder显示SegPC/2098.png\images/，貌似是这行的问题,可以请教下怎么修改吗

**Comment by xq141839** [comment]
那可能是你的数据集格式有问题？你数据集目录是怎么做的呀？

**Comment by 18834114892** [comment]
SegPC分为images和masks，并且images转为png格式了

**Comment by ttjjyys** [comment]
我尝试把这两句   image_folder = os.path.join(self.path,str(self.folders[idx]),'images/')
            mask_folder = os.path.join(self.path,str(self.folders[idx]),'masks/')改为image_folder = os.path.join(self.path, 'images/', str(self.folders[idx]))
            mask_folder = os.path.join(self.path, 'masks/', str(self.folders[idx]))结果还是显示    image_path = os.path.join(image_folder,os.listdir(image_folder)[0])
NotADirectoryError: [WinError 267] 目录名称无效。: 'SegPC/images/9418.png'

**Comment by ttjjyys** [comment]
之前的二分类都没遇到过这个问题

**Comment by xq141839** [comment]
我查看了我之前的代码，你可以尝试把多分类的图片读取按照二分类的来，多分类的原始数据结构和二分类的不一样

**Comment by xq141839** [comment]
├── data
          ├── image_0
                ├── images
                       ├── image_1.png
                ├── masks
                       ├── image_1.png
          ├── image_1
                ├── images
                        ├──....
                 ├── masks
                         ├── ...
          ├── ...

**Comment by ttjjyys** [comment]
> ```
> ├── data
>       ├── image_0
>             ├── images
>                    ├── image_1.png
>             ├── masks
>                    ├── image_1.png
>       ├── image_1
>             ├── images
>                     ├──....
>              ├── masks
>                      ├── ...
>       ├── ...
> ```

请问是按照这个格式每个文件夹放一张图片吗？那csv文件该怎么划分呢

**Comment by ttjjyys** [comment]
> ```
> ├── data
>       ├── image_0
>             ├── images
>                    ├── image_1.png
>             ├── masks
>                    ├── image_1.png
>       ├── image_1
>             ├── images
>                     ├──....
>              ├── masks
>                      ├── ...
>       ├── ...
> ```

十分感谢您之前的解答，除了csv的处理，我还想问一下您在使用SegPC时，网络的num_class设置的是2还是3呢

**Comment by xq141839** [comment]
csv文件就是每个图片文件夹的id比如这样
![image](https://github.com/user-attachments/assets/d8874801-ae6f-4d03-90f3-b62efbb358b3)

**Comment by xq141839** [comment]
num_class设置为3

**Comment by ttjjyys** [comment]
train_dataset = multi_classes(args.dataset,train_files, get_train_transform()) 
    val_dataset = multi_classes(args.dataset,val_files, get_valid_transform()) 
您好，train这里调用的时候是这样的吗，还是一直报错

**Comment by ttjjyys** [comment]
> ```
> ├── data
>       ├── image_0
>             ├── images
>                    ├── image_1.png
>             ├── masks
>                    ├── image_1.png
>       ├── image_1
>             ├── images
>                     ├──....
>              ├── masks
>                      ├── ...
>       ├── ...
> ```

不好意思，能烦请您把数据集格式截个图片给我看下吗，我可能还是布局有问题

**Comment by xq141839** [comment]
数据集目录
![image](https://github.com/user-attachments/assets/22feabe2-b403-46c6-9b28-433991f725b9)
某个image_id目录
![image](https://github.com/user-attachments/assets/1fe930fc-d331-4ff8-8bfc-5d801a317459)
images
![image](https://github.com/user-attachments/assets/428785cb-a39a-44b9-b01f-66530b4e7546)
masks
![image](https://github.com/user-attachments/assets/686bc159-296e-4089-9270-4dfaa0411271)

**Comment by ttjjyys** [comment]
> 数据集目录 ![image](https://private-user-images.githubusercontent.com/98734126/370991737-22feabe2-b403-46c6-9b28-433991f725b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczMzQzNjQsIm5iZiI6MTcyNzMzNDA2NCwicGF0aCI6Ii85ODczNDEyNi8zNzA5OTE3MzctMjJmZWFiZTItYjQwMy00NmM2LTliMjgtNDMzOTkxZjcyNWI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDA3MDEwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjZDE2YmRjZDJhYmY0ZjE0NWI3ZmI5MjVlMDZhOTNmMTU3NWYyMmYzNWY2MGUwMGViZTliMWVhM2MzN2FhZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.mLGBjDQ4FbB1k-f64pqZWFcHzdkmd_xl4CouawlVgqk) 某个image_id目录 ![image](https://private-user-images.githubusercontent.com/98734126/370991749-1fe930fc-d331-4ff8-8bfc-5d801a317459.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczMzQzNjQsIm5iZiI6MTcyNzMzNDA2NCwicGF0aCI6Ii85ODczNDEyNi8zNzA5OTE3NDktMWZlOTMwZmMtZDMzMS00ZmY4LThiZmMtNWQ4MDFhMzE3NDU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDA3MDEwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxYTJjNzI2ZmVkODRkZmMxNmNjZjQ5MGFhMWQ0ZWIxMGUwNjdhYTY3ZDUzMjMzMTU5OTFiNDM2YzlkNDYwYzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.cBV1iSakRSxYOT7B6lZ94WbAoEDk2zo7qxR_U3o4PWI) images ![image](https://private-user-images.githubusercontent.com/98734126/370991773-428785cb-a39a-44b9-b01f-66530b4e7546.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczMzQzNjQsIm5iZiI6MTcyNzMzNDA2NCwicGF0aCI6Ii85ODczNDEyNi8zNzA5OTE3NzMtNDI4Nzg1Y2ItYTM5YS00NGI5LWIwMWYtNjY1MzBiNGU3NTQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDA3MDEwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxY2M3ZGMwYzkzNTNmNGJjMjc1YTQxMWIxMTRiMmFiNDE5ZGFkODk1ZmUwNmZmOTBjMmM5YzNhYzUwYWQ4NDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xX5VGFmHPgJVCdSa2faRWKk735CKfZgRC5AkXEm85Z4) masks ![image](https://private-user-images.githubusercontent.com/98734126/370991788-686bc159-296e-4089-9270-4dfaa0411271.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczMzQzNjQsIm5iZiI6MTcyNzMzNDA2NCwicGF0aCI6Ii85ODczNDEyNi8zNzA5OTE3ODgtNjg2YmMxNTktMjk2ZS00MDg5LTkyNzAtNGRmYWEwNDExMjcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDA3MDEwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1NmIyM2UwNGMwNDFmNzczMTMwYWRiNzVkY2U1NDdhY2RmZmI3YjE5NWJkNTYyYTFlZmE0ZGI3ZjcxZmMzZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.29U-s3fPDpT07QLqMEqGyx0YSpT3nic3_VRRlc7AWk0)

感谢您为我解答这么多，我的代码能力太差了，还是改不通，想冒昧请您可以发我一下多分类的代码文件吗，我的邮箱是2453499915@qq.com      就算不方便发送，也十分感谢您了，谢谢

**Comment by 18834114892** [comment]
您好作者，我尝试更新了albumentations，变为引入tenserv2，报错改为mask尺寸问题

**Comment by 18834114892** [comment]
您好作者，我是修改dataloading中return (img_nl,mask,mask_nl,image_id) 修改成return (img_nl,mask,image_id)还是修改train中for inputs,labels,image_id in dataloaders[phase]:  ，若修改train这句，应该怎么修改呢

**Comment by ttjjyys** [comment]
不好意思作者，之前不该做伸手党的，麻烦您帮我看下这个问题
是将dataloading中return (img_nl,mask,mask_nl,image_id) 修改成return (img_nl,mask,image_id)或者return (img_nl,mask_nl,image_id), 
 还是修改train中for inputs,labels,image_id in dataloaders[phase]: ，若修改train这句，应该怎么修改呢，谢谢您

**Comment by 18834114892** [comment]
您好作者，冒昧在假期打扰您，这段我实在搞不懂，
这句换成注释内容#for inputs,labels,label_for_ce,image_id in dataloaders[phase]: 
            for inputs,labels,image_id in dataloaders[phase]:      
                # wrap them in Variable
                if torch.cuda.is_available():
                    
                    inputs = Variable(inputs.cuda())
                    labels = Variable(labels.cuda())
                   这句消除注释 #label_for_ce = Variable(label_for_ce.cuda())
                else:
                    inputs, labels = Variable(inputs), Variable(labels)
                
                # zero the parameter gradients
                optimizer.zero_grad()
           这句也消除注释 ，但是最后这没有被调用#label_for_ce = label_for_ce.long()
                # forward
                outputs = model(inputs)

                loss = criterion(outputs, labels)
                score = accuracy_metric(outputs,labels)但是如果我最后这两句调用，又会报错
期待您节后的回复，祝国庆假期快乐🥰

**Comment by xq141839** [comment]
如果你还没调通的话可以用monai的库进行替换，现在仓库里的代码是我手写的，可能有点复杂
